Python 3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> ("identity operators")
'identity operators'
>>> a=10
>>> if type(a) is not int:
...     print("true")
... 
...     
>>> if type(a) is int:
...     print("True")
... 
...     
True
>>> b=20
>>> if a is 10:
...     print("True")
... 
...     
True
>>> if b is not 20:
...     print("True")
... 
...     
